### ISSUE TITLE
The projects filter in the sliding menu doesn't work

### ISSUE THREAD

**Issue by sitaktif** [svijee/taskwarrior-androidapp#32] opened 2013-04-28 09:20 UTC
I have 2 tasks: one under the "proj1" project and one without project.

Selecting the "no project" button displays only task 2, but selecting the "proj1" project displays both task 1 and task 2. Expected: only task 1 is displayed.

**Comment by svijee** [comment] 2013-04-28 09:55
I can't reproduce this bug. It works fine for me. Are you using the current version?

**Comment by sitaktif** [comment] 2013-04-28 14:56
Yes, I'm pretty sure I'm using the current version (it uses the taskwarrior format)

Here are screenshots and my pending tasks file in case it helps

```
[description:"bar" entry:"1367140253" status:"pending" uuid:"7f387124-47b7-4362-9e52-8959d9285716"  end:"1367140253" ]
[description:"foo" entry:"1367140189" status:"pending" uuid:"874de27c-6ea2-4461-96ad-f119a760c3d3"  end:"1367140363" due:"1372374000" project:"proj1" priority:"M" ]
```

First screenshot to show what the menu looks like (there is no "all projects" btw!) and second one to show what happens if I click on the "proj1" button (it shows all the tasks).

![Screenshot_2013-04-28-12-15-20](https://f.cloud.github.com/assets/57383/435895/dd4fc598-b012-11e2-8699-51c723021f5d.png)
![Screenshot_2013-04-28-12-15-24](https://f.cloud.github.com/assets/57383/435894/dd31c9e4-b012-11e2-8dc6-dced9df172ca.png)

**Comment by svijee** [comment] 2013-04-28 15:04
Thanks for the details. I can reproduce it now.

**Comment by svijee** [comment] 2013-04-28 15:19
Should be fixed now. Please test it again. Thanks! :)

**Closed as completed** 2013-04-28 15:19 UTC

**Comment by sitaktif** [comment] 2013-04-29 07:53
I confirm it work now, cheers :+1:
